### ISSUE TITLE
Port SSE changes from harvester to hapi-harvester

### ISSUE THREAD

**Issue by mavdi** [agco/hapi-harvester#27]
- Make sure we use ```Mongoose``` instead of ```mongojs```
- add ```oplogReplay``` flag just as in
https://github.com/agco/harvesterjs/blob/develop/lib/sse.js#L131
- there is a problem with namespaces in query, we have to use the plural name of the resource in there, see this line https://github.com/agco/harvesterjs/blob/develop/lib/sse.js#L141

**Comment by kristofsajdak** [comment]
Hey @mavdi. Is this still relevant?
First 2 points are fixed as part of https://github.com/agco/hapi-harvester/pull/50

Might be wrong here, but the last one seems irrelevant for hapi-harvester as we don't have separ ate single and plural concepts any more, a resource is always plural and so is the mongodb collection.

**Comment by mavdi** [comment]
This issue is no longer relevant as SSE for ```hapi-harvester``` has been re-written.
