### ISSUE TITLE
Disable 'required' field rules for PATCHes

### ISSUE THREAD

**Issue by dclucas** [agco/hapi-harvester#33]
Say you have a brands contract that specifies two mandatory fields: code and description.

Say you want to update a brand, to fix a description typo (change 'Massey Furgeson' to 'Massey Ferguson'). If you patch the API with just the description, you will receive an error message saying that you failed to provide the code.

**Comment by mavdi** [comment]
Work assigned

**Comment by niahmiah** [comment]
https://github.com/agco/hapi-harvester/pull/66
