### ISSUE TITLE
Shouldn't we be more strict about Content-type

### ISSUE THREAD

**Issue by dclucas** [agco/hapi-harvester#36]
Really just a question. While the JSONAPI specs do not explicitly prohibit the use of any other content-type, the wording seems to indicate that just 'application/vnd.api+json' should be supported:

> Clients MUST send all JSON API data in request documents with the header Content-Type: application/vnd.api+json without any media type parameters.

**Comment by kristofsajdak** [comment]
yeah, seen this. I think that they mean that clients which pretend to be jsonapi 1.0 compliant must always send this. However as you say there is nothing that prohibits a server from accepting a plain old application/json content type as well
