### ISSUE TITLE
404 error codes on urls with trailing slashes

### ISSUE THREAD

**Issue by dclucas** [agco/hapi-harvester#37]
Run the sample code and try to do a GET at /brands/, keeping the trailing slash. API will return a 404.

**Comment by kristofsajdak** [comment]
Thanks for spotting this, however it doesn't seem like a harvester concern though. 

stripTrailingSlash is an option which can be set at the Hapi level : https://github.com/hapijs/hapi/issues/1576#issuecomment-94531951
