### ISSUE TITLE
API fails to show an error on mongodb connection issues

### ISSUE THREAD

**Issue by cborges82** [agco/hapi-harvester#42]
When is informed a wrong connection string and the connection with mongo fails, Harvest don't show any error message, only timeout when try to request message.

**Comment by kristofsajdak** [comment]
we solved this issue already in harvesterjs 
https://github.com/agco/harvesterjs/blob/develop/lib/adapters/mongodb.js#L14

I suggest we port this over as-is to hapi-harvester

**Comment by mavdi** [comment]
This is in progress.

**Comment by kristofsajdak** [comment]
should be fixed as part of this PR 
https://github.com/agco/hapi-harvester/pull/50?w=0
