### ISSUE TITLE
Able to POST data without an `attributes` field

### ISSUE THREAD

**Issue by dclucas** [agco/hapi-harvester#45]
The `attributes` field is not considered mandatory, even when child elements are. This means I can POST a payload containing only a type.

I do know this is as per JSON API spec, but on the other hand, the majority of cases would require *some* data to exist in the attributes.

We should either find a way to make the validation of the `attributes` field an overridable default or highlight in big, bright, red letters the fact that this field needs to be explicitly marked as required.

**Comment by mavdi** [comment]
Work assigned.

**Comment by niahmiah** [comment]
https://github.com/agco/hapi-harvester/pull/69

**Comment by kristofsajdak** [comment]
@niahmiah @dclucas Thinking through this issue a bit, does this actually add value?  

I could imagine we want to be able to support resource data with 'relationships' only. Apart from that most resources will have at least one required property, if one of the subordinate properties of the attributes is marked as required it should fail if absent.

Also wanted to bring up the point that this impacts the route schema definition, which makes it a pretty important change. Perhaps we should talk through the design a bit more before merging it in. 

Thoughts?

**Comment by ssebro** [comment]
I'd prefer that we don't add "features" that we don't actually use because every line of code adds support obligations and ongoing cost. I'm closing this ticket w/o merging - please reopen if you disagree.
